[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gem"
version = "1.0.0"
requires-python = ">=3.14"
dependencies = [
  "psycopg",
  "requests",
  "tabulate",
  "matplotlib",
  "pytest",
  "pytest-postgresql"
]

[project.scripts]
gem = "gem.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

