version: 2

models:
  - name: stg_items
    description: "Staging model for items"
    columns:
      - name: item_id
        data_tests:
          - unique
          - not_null
      - name: name
        data_tests:
          - not_null

  - name: stg_prices
    description: "Staging model for prices_1h"
    columns:
      - name: price_id
        data_tests:
          - unique
          - not_null
      - name: item_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_items')
                field: item_id
              config:
                severity: warn
